name: CI
on:
  - pull_request
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and test with Gradle
        working-directory: ./carrental 
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Build Docker image
        working-directory: ./carrental 
        run: |
          docker build -t carrental .
          docker images